### ISSUE TITLE
Unable to get IOS working on Mac M1

### ISSUE THREAD

**Issue by Cmdv** [wusyong/cargo-mobile#81]
Been trying for a good day but not able to get things to build, the following is my setup:

M1, MacOs 12.6, Xcode 14.2 (I even purchased an dev account so I could fill in the dev team section!!)

Here are the commands I ran 
```
> cargo install --git https://github.com/tauri-apps/tauri-mobile
> cargo mobile init
## install the wry template
```
Then to get things actually running, I've tried both of these:
```
> cargo apple build
> cargo build --target aarch64-apple-ios
```

The first fails with ios versions being too low at 9.0, I up those to 11.0 then the next error is:
```
ld: warning: directory not found for option '-L/Users/cmdv/Code/Beou/BeouApp/gen/apple/Sources/aarch64-apple-ios/debug'
ld: library not found for -lbeou_app
```
Then the second
```
the trait bound `Cow<'_, [u8]>: From<()>` is not satisfied
   --> src/lib.rs:123:72
```
If I simply cargo build then that works and I see an application window with a webpage!

sorry I'm new to Rust, I've come over from Haskell but really wanted to try out making an IOS/Android app in Rust rather than using a javascript framework

**Comment by wusyong** [comment]
Latest version of wry changed the return type to Cow. I thought I pushed an updated template for it already.
I'll be back from Lunar New Year next week to fix it. But if anyone is interested in this issue, feel free to take it.

**Comment by pewsheen** [comment]
The trait-bound issue should be fixed in #82

**Comment by Cmdv** [comment]
It didn't fix the odd: 
```ld: library not found for -lmyapp_name``` 
still haven't got it running locally 🤔

**Comment by pewsheen** [comment]
> It didn't fix the odd:
> `ld: library not found for -lmyapp_name`
> still haven't got it running locally 🤔

Could you try if `cargo build` first would solve the error?

```
cargo build --target aarch64-apple-ios
cargo apple run
```

Here is the [mobile setup document for Wry](https://github.com/tauri-apps/wry/blob/dev/MOBILE.md#build-and-run-on-device)

**Comment by Cmdv** [comment]
I'll have a go later this evening and report back 😄 thanks @pewsheen

**Comment by Cmdv** [comment]
sorry totally forgot to write back, so yes I have to do

```
cargo build --target aarch64-apple-ios
\\ or
cargo build --target aarch64-apple-ios-sim
```
and that seems to do the trick 🎉 

All we need now it hot reloading and everyone is a winner 😂
